# Generated by Django 4.2.5 on 2023-09-19 23:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tw_portfolio', '0002_education_social_workhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('main_heading', models.CharField(blank=True, max_length=100, null=True)),
                ('brief_description', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Heading',
        ),
    ]
