# Generated by Django 4.2.5 on 2023-09-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tw_portfolio', '0003_home_delete_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='detail_paragraph_3',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='studying',
        ),
    ]
