# Generated by Django 4.2.5 on 2023-09-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tw_portfolio', '0004_remove_personaldetail_detail_paragraph_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='social_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
