# Generated by Django 4.2.5 on 2023-09-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tw_portfolio', '0005_alter_social_social_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
