# Generated by Django 4.2.5 on 2023-09-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tw_portfolio', '0007_personaldetail_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_icon',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
