# Generated by Django 4.2.5 on 2023-09-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tw_portfolio', '0008_alter_skill_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
