# Generated by Django 4.2.5 on 2023-09-29 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tw_portfolio', '0009_education_end_date_education_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_competency',
        ),
    ]
