# Generated by Django 4.2.5 on 2025-02-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tw_portfolio', '0011_remove_home_main_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='brief_description',
        ),
    ]
