# Generated by Django 4.2.5 on 2025-02-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tw_portfolio', '0012_remove_home_brief_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_icon',
            field=models.URLField(max_length=120, null=True),
        ),
    ]
