# Generated by Django 4.2.5 on 2025-03-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tw_portfolio', '0013_alter_skill_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
